SELECT * FROM zudio.zudio_sales_data;

# What is the total revenue generated by each store?
SELECT Store, SUM(Price * Quantity) AS Total_Revenue FROM zudio_sales_data
GROUP BY Store;

#Which city's stores have the highest and lowest average sales profits?
(SELECT City, AVG(`Sales Profit`) AS Avg_Profit FROM Zudio_sales_data GROUP BY City 
ORDER BY Avg_Profit DESC LIMIT 1)
UNION ALL
(SELECT City, AVG(`Sales Profit`) AS Avg_Profit FROM Zudio_sales_data GROUP BY City 
ORDER BY Avg_Profit ASC LIMIT 1);

#What are the top 5 Clothing type contributing to overall revenue?
SELECT `Clothing Type`, SUM(Price * Quantity) AS Revenue FROM zudio_sales_data
GROUP BY `Clothing Type` ORDER BY Revenue DESC LIMIT 5;

#Which months have the highest and lowest sales profits?
(SELECT Month, SUM(`Sales Profit`) AS Total_Profit FROM zudio_sales_data GROUP BY Month
ORDER BY Total_Profit DESC LIMIT 1)
UNION ALL
(SELECT Month, SUM(`Sales Profit`) AS Total_Profit FROM zudio_sales_data GROUP BY Month
ORDER BY Total_Profit ASC LIMIT 1);

#How many customers are unique for each store?
SELECT Store, COUNT(DISTINCT `Customer ID`) AS Unique_Customers FROM zudio_sales_data GROUP BY Store;

#What is the total sales profit for each State?
SELECT State, SUM(`Sales Profit`) AS Total_Profit FROM zudio_sales_data GROUP BY State;

#Find the top 5 customers based on total sales profit.
SELECT `Customer Name`, SUM(`Sales Profit`) AS Total_Profit FROM Zudio_sales_data GROUP BY `Customer Name`
ORDER BY Total_Profit DESC LIMIT 5;

#What is the trend of sales profits over time (monthly)?
SELECT Month, SUM(`Sales Profit`) AS Total_Profit FROM zudio_sales_data GROUP BY Month
ORDER BY FIELD(Month, 'January', 'February', 'March', 'April', 'May', 'June',
'July', 'August', 'September', 'October', 'November', 'December');

#How many products were sold by each Clothing Type?
SELECT `Clothing Type`, SUM(Quantity) AS Total_Products_Sold FROM zudio_sales_data
GROUP BY `Clothing Type`;

#Which cities have the highest number of stores?
SELECT City, COUNT(*) AS Store_Count FROM Zudio_sales_data GROUP BY City 
ORDER BY Store_Count DESC;

#Which are the top 10 customers with highest order?
SELECT `Customer Name`, COUNT(`Order ID`) AS Total_Orders FROM Zudio_sales_data
GROUP BY `Customer Name` ORDER BY Total_Orders DESC LIMIT 10;

#Identify the top 3 states with the highest sales profits.
SELECT State, SUM(`Sales Profit`) AS Total_Profit FROM Zudio_sales_data GROUP BY State
ORDER BY Total_Profit DESC LIMIT 3;